include:
- scripts/dukkha/entrypoint.yaml

global:
  default_git_branch: master
  cache_dir: scripts/dukkha/cache
  env:
  - name: GLOBAL_ENV_FOO
    value: foo
  - name: GLOBAL_ENV_BAR
    value: ${GLOBAL_ENV_FOO}-bar

  values:
    testdata:
      __just_call_template@template: |-
        {{- dukkha.SetValue "testdata.render.a" "I'm a" -}}

      str_not_number@transform:
        value: "10.10000"
        ops:
        - template: |-
            {{- printf "str-%s" VALUE -}}

      render:
        # a: I'm a
        b:
          c@echo:
            d@template:
              e@http: |-
                https://gist.githubusercontent.com/arhatbot/{{- /* join */ -}}
                d1f27e2b6d7e41a7c9d0a6ef7e39a921/raw/{{- /* join */ -}}
                1e014333a3d78ac1139bc4cab9a68685e5080685/{{- /* join */ -}}
                echo.sh

renderers:
  http:
    enable_cache: true
    cache_max_age: 10s
  env:
    enable_exec: true

shells:
- name: bash
- name: python
