include:
- scripts/dukkha/entrypoint.yaml

global:
  default_git_branch: master
  cache_dir: scripts/dukkha/cache
  env:
  - name: GLOBAL_ENV_FOO
    value: foo
  - name: GLOBAL_ENV_BAR
    value: ${GLOBAL_ENV_FOO}-bar

renderers:
  http:
    enable_cache: true
    cache_max_age: 10s

shells:
- name: bash
- name: python
