include:
- scripts/dukkha/entrypoint.yaml

bootstrap:
  cache_dir: scripts/dukkha/cache
  env:
  - GIT_DEFAULT_BRANCH=master
  script_cmd: [sh]

renderers:
  http:
    enable_cache: true
    cache_max_age: 10s

shells:
- name: bash
- name: python
