include:
- cicd

renderers:
  http:
    enable_cache: true
    cache_max_age: 5h
  env:
    enable_exec: true

global:
  default_git_branch: master
  env:
  - name: GO_VERSION
    value: "1.17"
  values:
    cmd:
      run_container@http|template: https://raw.githubusercontent.com/arhat-dev/dukkha-presets/master/templates/cmd-run-container.yml

tools:
  workflow:
  - name: local
  - name: in-ctr

  golang:
  - name: local
  - name: in-ctr
    cmd@template|http|template: |-
      https://raw.githubusercontent.com/arhat-dev/dukkha-presets/master/
      {{- /* line sep */ -}}
      golang/cmd-in-ctr.yml

  cosign:
  - name: local
  # TODO: support in container cosign
  - name: in-ctr

  # docker is required by cosign upload (login to docker registry)
  docker:
  - name: local
  # TODO: support docker in docker
  - name: in-ctr

  github:
  - name: local
  - name: in-ctr

  buildah:
  - name: local
  - name: in-ctr
    cmd@template|http|template: |-
      https://raw.githubusercontent.com/arhat-dev/dukkha-presets/master/
      {{- /* line sep */ -}}
      buildah/cmd-in-ctr.yml
