include:
- scripts/dukkha/entrypoint.yaml

global:
  cache_dir: scripts/dukkha/cache
  env:
  - name: GIT_DEFAULT_BRANCH
    value: master

renderers:
  http:
    enable_cache: true
    cache_max_age: 10s

shells:
- name: bash
- name: python
