# yaml-language-server: $schema=./docs/generated/schema.json

include:
- path@echo: cicd

renderers:
- http:
    cache:
      enabled: true
      timeout: 5h

  env:
    enable_exec: true

  tpl:
    include:
    - path: cicd/artifacts/bin-name.tpl

- file:dukkha-presets:
    alias@tpl: |-
      {{- if env.LOCAL_DUKKHA_PRESETS_PATH -}}
        presets
      {{- end -}}
    base_path@env: ${LOCAL_DUKKHA_PRESETS_PATH:-".dukkha/cache/dukkha-presets"}

  http:dukkha-presets:
    alias@tpl: |-
      {{- if not env.LOCAL_DUKKHA_PRESETS_PATH -}}
        presets
      {{- end -}}
    cache:
      enabled: true
      timeout: 2h
    base_url: https://raw.githubusercontent.com/arhat-dev/dukkha-presets/dev/

global:
  default_git_branch: master
  env:
  - name: GO_VERSION
    value: "1.18"
  values:
    cmd:
      run_ctr@presets?str|tpl: templates/run-ctr.yml

tools:
  archive:
  - name: local
  - name: in-ctr

  workflow:
  - name: local
  - name: in-ctr

  golang:
  - name: local
  - name: in-ctr
    cmd@tpl#use-spec:
      template: |-
        {{- include "golang.cmd.ctr" . -}}
      include:
      - path@presets#cached-file: templates/image/flavored-tag.tpl
      - path@presets#cached-file: golang/cmd/ctr.yml

      variables:
        version@env?str: ${GO_VERSION}
        # run_ctr:

  cosign:
  - name: local
  - name: in-ctr
    cmd@tpl#use-spec:
      template: |-
        {{- include "cosign.cmd.ctr" . -}}
      include:
      - path@presets#cached-file?str: cosign/cmd/ctr.yml

  # docker is required by cosign upload (login to docker registry)
  docker:
  - name: local
  # TODO: support docker in docker
  - name: in-ctr

  github:
  - name: local
  - name: in-ctr

  buildah:
  - name: local
  - name: in-ctr
    cmd@tpl#use-spec:
      template: |-
        {{- include "buildah.cmd.ctr" . -}}

      include:
      - path@presets#cached-file?str: buildah/cmd/ctr.yml

      variables:
        run_ctr@tpl#use-spec:
          template@presets?str: templates/run-ctr.yml
          variables:
            privileged: true
        # version: latest
