global:
  values:
    renovate_values@file: values.yaml

renderers:
- http:
    cache:
      enabled: true
      size: 1G
      max_item_size: 1M
      timeout: 1h

  af:
    cache:
      enabled: true
      max_item_size: 1M
      timeout: 1h
      size: 1G
