global:
  # env values are resolved before values
  env:
  - name: nginx_version
    value: latest

  - name: kubernetes_version
    value@shell: |-
      kubectl version --output json | template:jq '".serverVersion.gitVersion"'

  values@!:
    value@file|tmpl: values.yaml
    merge:
    - value:
        versions:
          kubernetes@env: ${kubernetes_version}
          ingress@tmpl: |-
            {{- if semverCompare ">=1.19-0" env.kubernetes_version -}}
              networking.k8s.io/v1
            {{- else if semverCompare ">=1.14-0" -}}
              networking.k8s.io/v1beta1
            {{- else -}}
              extensions/v1beta1
            {{- end -}}
