// Code generated by 'yaegi extract arhat.dev/dukkha/pkg/sliceutils'. DO NOT EDIT.

package sliceutils_symbols

import (
	"arhat.dev/dukkha/pkg/sliceutils"
	"reflect"
)

func init() {
	Symbols["arhat.dev/dukkha/pkg/sliceutils/sliceutils"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"FormatStringMap": reflect.ValueOf(sliceutils.FormatStringMap),
		"NewStrings":      reflect.ValueOf(sliceutils.NewStrings),
	}
}
