// Code generated by 'yaegi extract arhat.dev/dukkha/pkg/matrix'. DO NOT EDIT.

package matrix_symbols

import (
	"arhat.dev/dukkha/pkg/matrix"
	"reflect"
)

func init() {
	Symbols["arhat.dev/dukkha/pkg/matrix/matrix"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CartesianProduct": reflect.ValueOf(matrix.CartesianProduct),

		// type definitions
		"Entry": reflect.ValueOf((*matrix.Entry)(nil)),
		"Spec":  reflect.ValueOf((*matrix.Spec)(nil)),
	}
}
