apiVersion: apps/v1
kind: Deployment
metadata:
  labels@file: &labels templates/labels.yaml
  name@tpl: "{{ values.name }}"
spec:
  replicas@tpl: "{{ values.replicas }}"
  selector:
    matchLabels@file: *labels
  template:
    metadata:
      labels@file: *labels
    spec@file: templates/core/v1/pod.spec.yaml
