apiVersion@tpl: "{{ .Values.versions.ingress }}"
kind: Ingress
metadata:
  name@tpl: "{{ .Values.name }}"
  labels@file: &labels templates/labels.yaml
spec@tpl|file: templates/{{ .Values.versions.ingress }}/ingress.spec.yaml
