apiVersion@template: "{{ .Values.versions.ingress }}"
kind: Ingress
metadata:
  name@template: "{{ .Values.name }}"
  labels@file: &labels templates/labels.yaml
spec@template|file: templates/{{ .Values.versions.ingress }}/ingress.spec.yaml
