apiVersion@tmpl: "{{ values.versions.ingress }}"
kind: Ingress
metadata:
  name@tmpl: "{{ values.name }}"
  labels@file: &labels templates/labels.yaml
spec@tmpl|file: templates/{{ values.versions.ingress }}/ingress.spec.yaml
