// Code generated by 'yaegi extract arhat.dev/dukkha/pkg/tools'. DO NOT EDIT.

package tools_symbols

import (
	"arhat.dev/dukkha/pkg/tools"
	"reflect"
)

func init() {
	Symbols["arhat.dev/dukkha/pkg/tools/tools"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetScriptCache": reflect.ValueOf(tools.GetScriptCache),
		"RunTask":        reflect.ValueOf(tools.RunTask),

		// type definitions
		"Action":           reflect.ValueOf((*tools.Action)(nil)),
		"BaseTask":         reflect.ValueOf((*tools.BaseTask)(nil)),
		"BaseTool":         reflect.ValueOf((*tools.BaseTool)(nil)),
		"BaseToolWithInit": reflect.ValueOf((*tools.BaseToolWithInit)(nil)),
		"TaskExecRequest":  reflect.ValueOf((*tools.TaskExecRequest)(nil)),
		"TaskHooks":        reflect.ValueOf((*tools.TaskHooks)(nil)),
	}
}
