tools:
  golang:
  - name: local
    env:
    - GO111MODULE=on
    - GO_PROXY=direct
    - GO_SUMDB=off
    cmd: [go]
  - name: linux-container
    # when using shell, you can leave environment variables unexpanded
    # and do extra scripting before actually run the tool
    use_shell: true
    shell_name: bootstrap
    cmd@template:
    - docker run -it --rm -v $(pwd):$(pwd) -w $(pwd)
    - ghcr.io/arhat-dev/builder-go:debian-{{ .Env.MATRIX_ARCH | default .Env.HOST_ARCH | trimSuffix "hf" }}
    - go

golang:build@file: .dukkha/go-build.yml
golang:test@template_file: .dukkha/go-test.yml
