tools:
  workflow:
  - name: local

workflow:run:
- name: github-ci
  jobs@template:
  - name: test dukkha working
    shell: echo test
  - name: gist
    shell@http: https://gist.githubusercontent.com/arhatbot/d1f27e2b6d7e41a7c9d0a6ef7e39a921/raw/1e014333a3d78ac1139bc4cab9a68685e5080685/echo.sh
  - name: build
    task: |-
      golang:build(dukkha, { kernel: [linux] })
