name: Build

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test
  pull_request:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    - "!deps/**"
  push:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    tags:
    - v*

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  build:
    if: contains(github.head_ref, 'deps/') == false
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - macos-latest
        # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 30m
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Build
      run: |
        make dukkha

        ./build/dukkha golang local build dukkha -j $(nproc --all)

    # - name: Package
    #   run: |
    #     make package.dukkha.linux.all

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

    - name: Build changelog
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v1.8.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # TODO: build changelog using convensional changelog
    - name: Create Release
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      env:
        CHANGELOG_SINCE: ${{ steps.build_changelog.outputs.fromTag }}
        CHANGELOG: ${{ steps.build_changelog.outputs.changelog }}
        # token is required by github cli (gh)
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make dukkha
        ./build/dukkkha github release dukkha
