name: CI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test
  pull_request:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    - "!deps/**"
  push:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    tags:
    - v*

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  stylecheck:
    if: contains(github.head_ref, 'deps/') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Ensure tidy gomod
      run: |
        make vendor
        if ! git diff --exit-code
        then
          echo "go mod not tidy"
          exit 1
        fi

    - name: Lint
      run: |
        make lint.all

  unit-tests:
    if: contains(github.head_ref, 'deps/') == false
    needs:
    - stylecheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Install qemu-static
      run: |
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        sudo apt update
        sudo apt install -y qemu-user-static

    - name: Test Packages
      env:
        # TODO: cannot get GIT_DEFAULT_BRANCH in github actions using actions/checkout
        #       set manually as a workaround
        GIT_DEFAULT_BRANCH: master
      run: |
        make test.pkg

    - name: Test Commands
      env:
        PUSH_DUKKHA_IMAGE_IN_CMD_TEST: "true"
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make test.cmd

    - uses: sonarsource/sonarqube-scan-action@v1.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
