name: CI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test
  pull_request:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    - "!deps/**"
  push:
    paths-ignore:
    - docs/**
    - cicd/deploy/charts/**
    - README.md
    branches:
    - master
    tags:
    - v*

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  stylecheck:
    if: contains(github.head_ref, 'deps/') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Ensure tidy gomod
      run: |
        make vendor
        if ! git diff --exit-code
        then
          echo "go mod not tidy"
          exit 1
        fi

    - name: Lint
      run: |
        make lint.all

  unit-tests:
    if: contains(github.head_ref, 'deps/') == false
    needs:
    - stylecheck
    strategy:
      matrix:
        include:
        - name: Test Packages
          target: test.pkg
          prepare: ""

        - name: Test Command And Upload Images
          target: test.cmd
          prepare: export PUSH_DUKKHA_IMAGE_IN_CMD_TEST="true"

        - name: Test Command And Upload blobs
          target: test.cmd
          prepare: export PUSH_DUKKHA_BLOB_IN_CMD_TEST="true"

      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: sigstore/cosign-installer@v1.0.0
      with:
        cosign-release: v1.0.0

    - name: Install qemu-static
      run: |
        sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

        sudo apt update
        sudo apt install -y qemu-user-static

    - name: ${{ matrix.name }}
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
        GHCR_USER: ${{ github.actor }}
        GHCR_PASS: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ${{ matrix.prepare }}

        make ${{ matrix.target }}

    - name: Remove dukkha cache
      if: always()
      run: |
        rm -rf scripts/dukkha/cache

    - uses: sonarsource/sonarqube-scan-action@v1.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # TODO: fix sonarqube server intermittent error
      continue-on-error: true
