global:
  env:
  - name: deployment_name
    value: nginx

  - name: replicas
    value: "1"
  - name: nginx_version
    value: latest
  - name: kubernetes_version
    value@shell: |-
      kubectl version --output json | template:jq \".serverVersion.gitVersion\"
  - name: ingress_api_version
    value@env|template: |-
      {{- if semverCompare ">=1.19-0" .Env.kubernetes_version -}}
        v1
      {{- else -}}
        v1beta1
      {{- end -}}
