package diff

import (
	"fmt"
	"strings"
)

// src is the yaml doc with rendering suffix
// original is the yaml doc generated by rendering src (up to date)
// current is the yaml doc altered based on the original doc
func ReasonDiff(src *Node, diffEntries []*Entry) []*Entry {
	// now we have found some differences between original and current yaml doc
	// reason cause of these differences

	for _, d := range diffEntries {
		node, exact := src.Get(d.Key)
		if !exact {
			// TODO: check rendering suffix
			fmt.Println(fmt.Sprintf("src is not compatible with key %v", d.Key))
			continue
		}

		switch d.Kind {
		case KindAdded:
			fmt.Println(fmt.Sprintf("ADD: %s", strings.Join(d.DivertAt.Key(), "")))
		case KindDeleted:
			fmt.Println(fmt.Sprintf("DEL: %s", strings.Join(d.Key, "")))
		case KindUpdated:
			fmt.Println(fmt.Sprintf("UPD: %s", strings.Join(d.Key, "")))
		}
		_ = node
	}

	return diffEntries
}
